// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYSnoopy2NHWxumEtHmvytxlg0cz-mXdQ',
    appId: '1:128473677770:web:35b341bbda515aa5cc5933',
    messagingSenderId: '128473677770',
    projectId: 'summarizer-1d885',
    authDomain: 'summarizer-1d885.firebaseapp.com',
    storageBucket: 'summarizer-1d885.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3W4uqzsIKTTxxY5ZRg1RsZFNmEVqWr0',
    appId: '1:128473677770:android:6651782a33c5e7b8cc5933',
    messagingSenderId: '128473677770',
    projectId: 'summarizer-1d885',
    storageBucket: 'summarizer-1d885.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjGhtpYCd4fAdFFfvbC-XrqunYeZoGofY',
    appId: '1:128473677770:ios:823ebe83cd6cfea5cc5933',
    messagingSenderId: '128473677770',
    projectId: 'summarizer-1d885',
    storageBucket: 'summarizer-1d885.appspot.com',
    iosClientId: '128473677770-m55e4fauneh8lfu91062d8oj4jslpfoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.summarizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjGhtpYCd4fAdFFfvbC-XrqunYeZoGofY',
    appId: '1:128473677770:ios:823ebe83cd6cfea5cc5933',
    messagingSenderId: '128473677770',
    projectId: 'summarizer-1d885',
    storageBucket: 'summarizer-1d885.appspot.com',
    iosClientId: '128473677770-m55e4fauneh8lfu91062d8oj4jslpfoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.summarizer',
  );
}
